War
CSC207-UofT/course-project-the-losers-club pull request #75
Opened 2021-11-10 02:01 UTC by Bradley-Mathi

This is the full game code for war. Everything should be in working order in terms of code and commenting. Once this is merged to the actual branch we can complete the tests for it 👌 .

2021-11-10 02:22 UTC, Luke-Avveduto commented on src/main/java/usecases/War.java
> +            this.gameOutput.sendOutput(players[1].getName() + " is out of cards and can no longer participate. " + players[0].getName() + " wins!");
Consider pulling this out into a private method to reduce the length of this method.

2021-11-10 02:24 UTC, raylfli requested changes
Also, run the IntelliJ code formatter to fix spacing issues

2021-11-10 02:24 UTC, raylfli commented on src/main/java/usecases/War.java
> +import java.util.*;
Consider reducing this import to just a single class

2021-11-10 02:26 UTC, Luke-Avveduto requested changes
Try pulling main into the branch, this should give the features you need to complete the tests. Then once the tests are added, push them and mark it for review again.

2021-11-10 02:26 UTC, Luke-Avveduto commented on src/main/java/usecases/War.java
> +
Consider pulling some larger code blocks into private helper methods, such as the chunks 110-120 and 81-95

2021-11-13 03:13 UTC, raylfli requested changes
In addition to the comments, 
* [ ] Add War to the `GameTemplate.gameFactory()` method and add War into the game list in `Main`
* [ ] Fix console output formatting
* [ ] Check all IntelliJ warnings
* [ ] Run the code formatter on all changed files

2021-11-13 03:13 UTC, raylfli commented on src/main/java/usecases/War.java
> +    public final ArrayList[] playingField = new ArrayList[]{new ArrayList<Card>(), new ArrayList<Card>()};
This should not be public. Additionally, check the IntelliJ warnings here

2021-11-13 03:13 UTC, raylfli commented on src/main/java/usecases/War.java
> +    private final static String[] Hierarchy = new String[]{"A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"};
Variable naming convention not adhered to here; constants should be all capitals

2021-11-13 03:13 UTC, raylfli commented on src/main/java/usecases/War.java
> +    public War(Input gameInput, Output gameOutput, List<String> usernames, UserManager userManager, Random random) {
Consider adding a constructor that does not have a `Random` parameter; look at `CrazyEights` for an example

2021-11-13 16:43 UTC, raylfli requested changes
Not all cards removed off piles after a turn

2021-11-13 16:43 UTC, raylfli commented on src/main/java/usecases/War.java
> +            }
Weird behaviour occurring here: 
```
=======================================
              GAME SELECT              
=======================================
[1] Crazy Eights
[2] War
[0] EXIT
=======================================
Make a selection: 2
Input up to 2 usernames for players playing the game. Enter 'done' to finish.
Enter a Username: alpha
Enter a Username: beta
=======================================




=======================================
                  War
=======================================




---------------------------------------
Turn 1. Pile sizes: 0
---------------------------------------
alpha's Pile is empty
---------------------------------------
beta's Pile is empty
---------------------------------------
Press enter to continue: 
---------------------------------------
alpha flipped the card 8D
beta flipped the card AC
alpha's card outranks their opponents and they win the battle!
---------------------------------------
Press enter to continue: 
---------------------------------------
Turn 2. Pile sizes: 0
---------------------------------------
alpha's Pile is empty
---------------------------------------
beta's Pile is empty
---------------------------------------
Press enter to continue: 
---------------------------------------
alpha flipped the card 10H
beta flipped the card 9H
alpha's card outranks their opponents and they win the battle!
---------------------------------------
Press enter to continue: 
---------------------------------------
Turn 3. Pile sizes: 0
---------------------------------------
alpha's Pile is empty
---------------------------------------
beta's Pile is empty
---------------------------------------
Press enter to continue: 
---------------------------------------
alpha flipped the card 2H
beta flipped the card 2S
Both players have flipped the same rank of card, so war begins!
---------------------------------------
Press enter to continue: 
---------------------------------------
Turn 4. Pile sizes: 1
---------------------------------------
alpha's Top Card is: 2H
---------------------------------------
beta's Top Card is: 2S
---------------------------------------
Press enter to continue: 
---------------------------------------
alpha flipped the card 4C
beta flipped the card QC
beta's card outranks their opponents and they win the battle!
---------------------------------------
Press enter to continue: 
---------------------------------------
Turn 5. Pile sizes: 1
---------------------------------------
alpha's Top Card is: 2D
---------------------------------------
beta's Top Card is: 6H
---------------------------------------
Press enter to continue: 
---------------------------------------
alpha flipped the card 3C
beta flipped the card AD
alpha's card outranks their opponents and they win the battle!
---------------------------------------
Press enter to continue: ```

2021-11-13 19:00 UTC, raylfli approved these changes
Concerns addressed

2021-11-13 19:02 UTC, merged